/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Vulkan_Game;
import Vulkan_Game.Vulkan;

public class App {
    public static void main(String[] args) {
        Vulkan vulkan = new Vulkan();
        vulkan.activate();
    }
}
